sudo: false

language: java

jdk:
  - oraclejdk8

install:	
  - ./gradlew jar

script: true

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" &&
    git config --global user.name "Travis CI" && git config --global user.email bpetri@gmx.net &&
    git clone https://github.com/INAETICS/bundles.git $TRAVIS_BUILD_DIR/bundles && cd $TRAVIS_BUILD_DIR/bundles &&
    git config credential.helper "store --file=.git/credentials" && echo "https://$GITHUB_TOKEN:@github.com" > .git/credentials &&
    cp $TRAVIS_BUILD_DIR/org.inaetics.wiring/generated/*.jar $TRAVIS_BUILD_DIR/bundles/default-resources &&
    git add default-resources/*.jar && git commit -m "build $TRAVIS_REPO_SLUG $TRAVIS_COMMIT" && git push -f 
